gcp_project               = "de-datapipeline"
gcp_region                = "asia-southeast1 "
gcs_bucket_location       = "Asia"
gcs_bucket_terraform      = "de-zoomcamp-terraform-state-backend"
#credentials               = "key.json"