name: 'Deploy kafka to GCE'

on:
  push:
    paths: 
    - 'kafka/**'
    branches: [ "main" ]
  pull_request:
    paths: 
    - 'kafka/**'
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  kafka:
    name: 'kafka'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ./kafka
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: export necessary variable to github env
      run: |
        TFVARS_FILE=${GITHUB_WORKSPACE}/terraform/terraform.tfvars
        export GCP_PROJECT_ID=$(grep 'gcp_project' $TFVARS_FILE | awk -F= '{print $2}' | tr -d '[:space:]' | tr -d '"')
        export KAFKA_INSTANCE=$(grep 'kafka_instance_name' $TFVARS_FILE | awk -F= '{print $2}' | tr -d '[:space:]' | tr -d '"')
        export KAFKA_INSTANCE_ZONE=$(grep 'kafka_instance_zone' $TFVARS_FILE | awk -F= '{print $2}' | tr -d '[:space:]' | tr -d '"')
        export KAFKA_CONTROL_PORT=$(grep 'kafka_control_port' $TFVARS_FILE | awk -F'[:=]' '{print $2}' | tr -d '[:space:]' | tr -d '[]"')

        export GITHUB_REPOSITORY=${GITHUB_REPOSITORY}

        echo GCP_PROJECT_ID=$GCP_PROJECT_ID >> $GITHUB_ENV
        echo KAFKA_INSTANCE=$KAFKA_INSTANCE >> $GITHUB_ENV
        echo KAFKA_INSTANCE_ZONE=$KAFKA_INSTANCE_ZONE >> $GITHUB_ENV
        echo KAFKA_CONTROL_PORT=$KAFKA_CONTROL_PORT" >> $GITHUB_EN
        echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" >> $GITHUB_ENV
        echo "GITHUB_REPO_NAME=$(basename -s .git $GITHUB_REPOSITORY)" >> $GITHUB_ENV

        echo "GCP_PROJECT_ID: $GCP_PROJECT_ID"
        echo "KAFKA_INSTANCE: $KAFKA_INSTANCE"
        echo "KAFKA_INSTANCE_ZONE: $KAFKA_INSTANCE_ZONE"
        echo "KAFKA_CONTROL_PORT: $KAFKA_CONTROL_PORT"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "GITHUB_REPO_NAME: $GITHUB_REPO_NAME"

    - name: remove existing repo in GCE
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name:  ${{ env.KAFKA_INSTANCE }}
        zone: ${{ env.KAFKA_INSTANCE_ZONE }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: 'rm -rf ${{ env.GITHUB_REPO_NAME }}'


    - name: cloning git repository into compute engine
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name:  ${{ env.KAFKA_INSTANCE }}
        zone: ${{ env.KAFKA_INSTANCE_ZONE }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: 'git clone https://github.com/${{ env.GITHUB_REPOSITORY }}.git'


    - name: apt update
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name:  ${{ env.KAFKA_INSTANCE }}
        zone: ${{ env.KAFKA_INSTANCE_ZONE }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: 'sudo apt-get update'

    - name: install docker
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name:  ${{ env.KAFKA_INSTANCE }}
        zone: ${{ env.KAFKA_INSTANCE_ZONE }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: 'sudo apt-get install -y docker.io docker-compose'

    - name: edit user permission
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name:  ${{ env.KAFKA_INSTANCE }}
        zone: ${{ env.KAFKA_INSTANCE_ZONE }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: 'sudo usermod -aG docker $USER'

    - name: reboot
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name:  ${{ env.KAFKA_INSTANCE }}
        zone: ${{ env.KAFKA_INSTANCE_ZONE }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: 'sudo reboot'
      continue-on-error: true

    - name: Delay Step
      run: sleep 60  # This will add a 60-second delay
        
    - name: run kafka
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name:  ${{ env.KAFKA_INSTANCE }}
        zone: ${{ env.KAFKA_INSTANCE_ZONE }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: 'docker-compose -f ${{ env.GITHUB_REPO_NAME }}/kafka/docker-compose.yml up -d'

    - name: Export the external IP of the Instance
      id: external-ip
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name: ${{ env.KAFKA_INSTANCE }}
        zone: ${{ env.KAFKA_INSTANCE_ZONE }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: 'echo "EXTERNAL_IP=$(curl -s ifconfig.co)" >> $GITHUB_OUTPUT'
    
    - name: show kafka control center link
      env:
        EXTERNAL_IP: ${{ steps.external-ip.outputs.EXTERNAL_IP }}
      run: echo "Kafka Successfully deployed, access control center in http://$EXTERNAL_IP:${{ env.KAFKA_CONTROL_PORT }}"