name: 'Deploy kafka to GCE'

on:
  push:
    paths: 
    - 'kafka/**'
    branches: [ "main" ]
  pull_request:
    paths: 
    - 'kafka/**'
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  kafka:
    name: 'kafka'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ./kafka
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use TFVars
      run: |
        TFVARS_FILE=${GITHUB_WORKSPACE}/terraform/terraform.tfvars
        GCP_PROJECT=$(grep 'gcp_project' $TFVARS_FILE | awk -F= '{print $2}' | tr -d '[:space:]')
        KAFKA_INSTANCE=$(grep 'kafka_instance_name' $TFVARS_FILE | awk -F= '{print $2}' | tr -d '[:space:]')
        KAFKA_INSTANCE_ZONE=$(grep 'kafka_instance_zone' $TFVARS_FILE | awk -F= '{print $2}' | tr -d '[:space:]')

        echo "GCP_PROJECT: $GCP_PROJECT"
        echo "KAFKA_INSTANCE: $KAFKA_INSTANCE"
        echo "KAFKA_INSTANCE_ZONE" : $KAFKA_INSTANCE_ZONE

    - name: Generate SSH Key
      run: |
        ssh-keygen -t rsa -b 4096 -C "ilhamaulanap@gmail.com" -f $HOME/.ssh/github_action_key -N ''

    - name: Display Public Key
      run: |
        cat $HOME/.ssh/github_action_key.pub
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Run Commands on GCP Instance
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name: $KAFKA_INSTANCE
        zone: $KAFKA_INSTANCE_ZONE
        ssh_private_key: $HOME/.ssh/github_action_key
        command: |
          git clone https://github.com/ilhamaulanap/DE-zoomcamp.git
          cd "$(basename "ilhamaulanap/DE-zoomcamp")/kafka"
          sudo apt-get update
          sudo apt-get install -y docker.io
          docker-compose build
          docker-compose up -d
