name: 'Create GCP Infrastructure (/Terraform)'

on:
  push:
    paths: 
    - 'kafka/**'
    branches: [ "main" ]
  pull_request:
    paths: 
    - 'kafka/**'
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: 'kafka'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ./kafka
        shell: bash
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Load Terraform Configuration
        run: |
          export $(terraform output -json | jq -r 'to_entries | map("\(.key)=\(.value.value)") | .[]')

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: $gcp_project 
          compute_region: $gcp_region

