name: 'Deploy kafka to GCE'

on:
  push:
    paths: 
    - 'kafka/**'
    branches: [ "main" ]
  pull_request:
    paths: 
    - 'kafka/**'
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  kafka:
    name: 'kafka'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ./kafka
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: export necessary variable to github env
      run: |
        TFVARS_FILE=${GITHUB_WORKSPACE}/terraform/terraform.tfvars
        export GCP_PROJECT_ID=$(grep 'gcp_project' $TFVARS_FILE | awk -F= '{print $2}' | tr -d '[:space:]' | tr -d '"')
        export KAFKA_INSTANCE=$(grep 'kafka_instance_name' $TFVARS_FILE | awk -F= '{print $2}' | tr -d '[:space:]' | tr -d '"')
        export KAFKA_INSTANCE_ZONE=$(grep 'kafka_instance_zone' $TFVARS_FILE | awk -F= '{print $2}' | tr -d '[:space:]' | tr -d '"')

        export GITHUB_REPOSITORY=${GITHUB_REPOSITORY}

        echo GCP_PROJECT_ID=$GCP_PROJECT_ID >> $GITHUB_ENV
        echo KAFKA_INSTANCE=$KAFKA_INSTANCE >> $GITHUB_ENV
        echo KAFKA_INSTANCE_ZONE=$KAFKA_INSTANCE_ZONE >> $GITHUB_ENV
        echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" >> $GITHUB_ENV

        echo "GCP_PROJECT_ID: $GCP_PROJECT_ID"
        echo "KAFKA_INSTANCE: $KAFKA_INSTANCE"
        echo "KAFKA_INSTANCE_ZONE: $KAFKA_INSTANCE_ZONE"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"

    - name: Run Commands on GCP Instance
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name:  ${{ env.KAFKA_INSTANCE }}
        zone: ${{ env.KAFKA_INSTANCE_ZONE }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git
          cd "$(basename "${GITHUB_REPOSITORY}")/kafka"
          sudo apt-get update
          sudo apt-get install -y docker.io
          docker-compose build
          docker-compose up -d
